[project]
name = "b3d"
description = ""
version = "0"
license = { text = "Apache 2.0" }
requires-python = ">= 3.10"
dependencies = []

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]
#conda-pypi-map = { "pytorch" = "torch_mapping.json" }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.pypi-dependencies]
b3d = { path = ".", editable = true }

[tool.pixi.environments]
cpu = { features = [], solve-group = "default" }
gpu = { features = ["core", "cuda"], solve-group = "cuda" }

[tool.pixi.activation.env]
XLA_PYTHON_CLIENT_PREALLOCATE = "false"
XLA_PYTHON_CLIENT_ALLOCATOR = "platform"
CPLUS_INCLUDE_PATH = "$CONDA_PREFIX/targets/x86_64-linux/include"

[tool.pixi.pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = [
    "https://oauth2accesstoken@us-west1-python.pkg.dev/probcomp-caliban/probcomp/simple",
    "https://download.pytorch.org/whl/cu121",
]

[tool.pixi.feature.core.pypi-dependencies]
pykitti = "==0.3.1"
pyliblzfse = ">=0.4.1,<0.5"
pyransac3d = ">=0.6.0,<0.7"

[tool.pixi.feature.core.dependencies]
distinctipy = ">=1.3.4,<1.4"
ffmpeg = "*"
fire = ">=0.6.0,<0.7"
imageio = "*"
ipykernel = "*"
ipython = ">=8.26.0,<8.27"
jupyter = ">=1.0.0,<1.1"
jupyterlab = "*"
jupytext = "*"
matplotlib = ">=3.9.1,<3.10"
natsort = ">=8.4.0,<8.5"
numpy = "<2.0.0"
ninja = "*"
pdoc3 = ">=0.11.1,<0.12"
pillow = "==10.3.0"
polars = ">=0.20,<0.21"
pyright = "*"
pytest = "*"
python-lzf = "*"
py-opencv = "*"
rerun-sdk = "==0.17.0"
ruff = "*"
scikit-learn = ">=1.5.1,<1.6"
scipy = ">=1.14.0,<1.15"
trimesh = "==4.2.4"
tqdm = "*"

[tool.pixi.feature.cuda]
platforms = ["linux-64"]
system-requirements = { cuda = "12" }

[tool.pixi.feature.cuda.target.linux-64.pypi-dependencies]
carvekit = "==4.1.2"

[tool.pixi.feature.cuda.target.linux-64.dependencies]
cuda-toolkit = "*"
gcc = "*"
jax = "*"
jaxlib = { version = "0.4.28", build = "cuda12*" }
libnvjitlink = "*"
optax = ">=0.2.2,<0.3"
pytorch = { version = "==2.3.0", build = "cuda12*" }
torchvision = "*"
